# Generated by Django 3.0.6 on 2020-05-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titles',
            new_name='title',
        ),
    ]
